// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygqydhwyshehroezfkgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncXlkaHd5c2hlaHJvZXpma2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjM2MTMsImV4cCI6MjA3NDYzOTYxM30.06eMLibuvHhOFadyWmJOUUA-XMwbppdqCHicEPM1XLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});